### ISSUE TITLE
Add time to `add` feature

### ISSUE THREAD

**Issue by BuJo** [synyx/buchungsstreber#115]
As someone with a dependence on more information, it would be good to add the time the entry was added into the entry comment.

**Comment by dgrammlich** [comment]
I made a scribble, but I do not like the position of the timestamp. I find it hard to read. Do you have a favorite place to put it? I thought about putting it under the added entry like this:

```
# comment
- 0.5
# Added on 2023-06-16 12:29:07 +0200
```

so it wraps the entry. Put I lack the Ruby skills. 😄 Maybe another time format also would help to improve the readability.

**Comment by BuJo** [comment]
```
% asdfasdf (added on 2023-06-16 12:29)
```
