### ISSUE TITLE
Time unit is sometimes shown twice in watch mode

### ISSUE THREAD

**Issue by dgrammlich** [synyx/buchungsstreber#27]
The time unit `h` is sometimes shown twice in watch mode.

![bs-watch-1](https://user-images.githubusercontent.com/5312377/96901799-0239f480-1494-11eb-9acf-9743e4538730.png)

The entry in the screenshot is an aggregated entry.

----

Buchungsstreber `2.4.0`
Ubuntu `18.04.5`
Ruby `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]` with
* curses `1.3.2`
* rb-inotify `0.10.1`

**Comment by dgrammlich** [comment]
> The entry in the screenshot is an aggregated entry.
 This does not seem to be the problem. I have this flaw also with non aggregated entries.

But it seems to be the first entry in the list that has the second `h`.

**Comment by BuJo** [comment]
Most likely it's an artifact on how the characters are drawn with ncurses without clearing the line first.

**Comment by BuJo** [comment]
Yes, I can see that in the code.  `tui.rb` starting from 99, it just assumes there is no content and will just draw the columns.
