### ISSUE TITLE
Redmine development setup

### ISSUE THREAD

**Issue by dgrammlich** [synyx/buchungsstreber#30]
As a developer I do not want to run my development environment against a productive Redmine. There is a [Redmine docker setup from Bitnami](https://github.com/Bitnami/bitnami-docker-redmine#run-the-application-using-docker-compose). It would be nice if there already were some Redmine issues created so maybe it could be enriched with some data. A example developer configuration and a example developer timesheet file also would be great.

**Comment by BuJo** [comment]
Hmm... unsure what is asked here.

Is this meant as a 'real instance' for explorative testing, or for automated integration testing?

**Comment by dgrammlich** [comment]
I thought of both somehow, but first of all I wanted to be able to test implementations explorative. Hm, and I also want to be able to develop and test my code without having access to an up and running Redmine.

**Comment by dgrammlich** [comment]
We expect Buchungsstreber users and developers to have access to a Redmine instance with the possibility to create an issue and add a time entry.
