### ISSUE TITLE
Built-in generator documentation

### ISSUE THREAD

**Issue by BuJo** [synyx/buchungsstreber#57]
It should be possible to configure a new generator without having to read the sourcecode.

**Comment by dgrammlich** [comment]
Do you mean documentation for how to write your own generator (class), like a tutorial for developers?

Or do you mean documentation for the already existing (_built-in_) generators in  `lib/buchungsstreber/generator` and as [already made for `ncalcli`](https://github.com/synyx/buchungsstreber/blob/main/doc/generatoren.md#importiere-nextcloud---owncloud-termine-per-ncalcli)?

Or - something completely different? 😄

**Comment by BuJo** [comment]
I mean user documentation.  The feature is quite hidden and it could be advertised a little bit more.

**Comment by BuJo** [comment]
The git generator docs could benefit from:

- dirs is a symbol
- `~` is resolved by shell only
- It only looks for git dirs 5 levels deep
